#!/bin/bash
cd ./scripts

if [ "$1" == "bootstrap" ]
    then 
        ./bootstrap.sh
fi

if [ "$1" == "start" ]
    then
        ./start.sh
fi

if [ "$1" == "restart" ]
    then
        ./restart.sh
fi

if [ "$1" == "stop" ]
    then 
        ./stop.sh
fi

if [ "$1" == "version" ]
    then 
        ./version.sh $*
fi

if [ "$1" == "publish" ]
    then 
        ./publish.sh $*
fi

if [ "$1" == "yarn" ]
    then 
        ./app.sh $*
fi

cd ../