#!/bin/bash
cd ./scripts

if [ "$1" == "bootstrap" ]
    then 
        ./bootstrap
fi

if [ "$1" == "start" ]
    then
        ./start
fi

if [ "$1" == "restart" ]
    then
        ./restart
fi

if [ "$1" == "stop" ]
    then 
        ./stop
fi

if [ "$1" == "version" ]
    then 
        ./version $*
fi

if [ "$1" == "publish" ]
    then 
        ./publish $*
fi

if [ "$1" == "yarn" ]
    then 
        ./app $*
fi

cd ../